주문 접수 완료 API
f-lab-edu/hee-commerce pull request #8
Opened 2023-04-26 15:30 UTC by daadaadaah

# What
- #9   

# Comment
- 일단 오늘 작업한거까지만 PR 올려봤어요!
- Rest API 구조는 #9 에 스샷 찍어 놨어요~
- 그리고, 작업단위로 한꺼번에 올리지 않고, 매일매일 조금씩 작업한거 올릴 것 같아요! 중간중간 빠진 거 체크하기 좋을 것 같아서요!
- 또한, 다음에는 아래 내용을 공부해볼 예정입니다.
1. 예외처리 + validation 공부하기 : 재고량 보다 주문 수량이 많은 경우 예외 던져서 처리하기
2. 현재 1건만 주문 접수 완료를 처리하는데, 여러건(최대 100건) 한꺼번에 처리하는 API 만들어보기
3. flyway로 정해진 데이터 스키마 코드화하기 -> 코드 작업해보니까 계속 스키마 구조를 보기 위해 draw.io를 들어가야 하는 불편함이 있어서, flyway로 코드화 시켜 놓으면 좋을 것 같아서 작업합니다.

2023-04-26 15:53 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderController.java
> +        orderService.completeOrderReceipt(order_uuid);
`order_uuid`를 `@PathVariable`에서 가져오는게 아니라, `orderService.completeOrderReceipt(order_uuid);`에서 return 해줘서 클라이언트한테 보내주는게 나을까요?

2023-04-26 16:31 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderController.java
> +    public ResponseEntity<CompleteOrderReceiptResponse> completeOrderReceipt(@PathVariable("order_uuid") UUID order_uuid) {
숫자로 요청했을 때, 다음과 같이 400 나오는데, 이에 대해 유효성 검사나 테스트 코드가 필요할까요?
<img width="898" alt="스크린샷 2023-04-27 오후 3 19 24" src="https://user-images.githubusercontent.com/60481383/234776256-23594101-c5a4-429e-bffc-1cc4ab1a4328.png">

2023-04-27 15:38 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderController.java
> +    public ResponseEntity<CompleteOrderReceiptResponse> completeOrderReceipt(@PathVariable("order_uuid") UUID order_uuid) {
예외 공부 후 다시 생각해보기

2023-04-28 21:26 UTC, f-lab-TJ requested changes

2023-04-28 21:26 UTC, f-lab-TJ commented on src/main/java/com/hcommerce/heecommerce/common/AuthInterceptor.java
> +        if (session == null || session.getAttribute("isAdmin") == null || !(boolean) session.getAttribute("isAdmin")) {
Or case의 뒤에 두개 차이는 뭔가요?

2023-04-28 21:26 UTC, f-lab-TJ commented on src/main/java/com/hcommerce/heecommerce/order/CompleteOrderReceiptResponse.java
> +    UUID order_uuid;
Admin이 CompleteOrderReceipt를 했지만 실패한 경우도 있을 수 있는데, 그런 경우는 UUID를 어떻게 하나요?
혹시 Lombok의 NonNull과 Nullable에 대해 공부해보신 적 있을까요? @daadaadaah @godtaehee

2023-04-28 21:26 UTC, f-lab-TJ commented on src/main/java/com/hcommerce/heecommerce/order/OrderController.java
> +    public ResponseEntity<CompleteOrderReceiptResponse> completeOrderReceipt(@PathVariable("order_uuid") UUID order_uuid) {
발생할 수 있는 예외에 대한 유닛 테스트 케이스 작성이 필요합니다.

2023-04-28 21:26 UTC, f-lab-TJ commented on src/main/java/com/hcommerce/heecommerce/order/OrderController.java
> +        orderService.completeOrderReceipt(order_uuid);
프론트 개발자 입장에서 어떤 메세지와 값이 더 유용할까요?

2023-04-28 21:26 UTC, f-lab-TJ commented on src/test/java/com/hcommerce/heecommerce/common/AuthInterceptorTest.java
> +class AuthInterceptorTest {
필요하다면 `@Test(expected =` 를 annotation을 사용해보세요. https://www.baeldung.com/junit-assert-exception

2023-04-29 06:55 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/common/AuthInterceptor.java
> +        if (session == null || session.getAttribute("isAdmin") == null || !(boolean) session.getAttribute("isAdmin")) {
1. 이 경우는 로그인 하지 않는 사용자가 요청한 경우에 대한 것이고,
```java
session.getAttribute("isAdmin")
```
2. 이 경우는 로그인은 했지만, 사용자가 관리자가 아닌 일반 구매자인 경우에 대한 것입니다.
```java
!(boolean) session.getAttribute("isAdmin")
```

2023-04-29 07:24 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderController.java
> +        orderService.completeOrderReceipt(order_uuid);
"주문 접수가 완료되었습니다."로 보내주는게 좀더 프론트 개발자 입장에서 더 유용할 것 같습니다.
그래서, 생각해본게 response를 태희님과 상의해서 템플릿화 하면 어떨까? 라는 생각이 들었는데, TJ 의견은 어떤지 궁금합니다.
구조는 다음과 같습니다.
```java
{
   isSuccess -> 성공하면 true이고 실패하면 false,
   code: -> HTTP 코드 참고해서 작성해볼 것 같아요!
   message: -> 웹 사이트의 alert 창에 사용될만한 메시지
   data: -> 클라이언트에서 필요한 데이터가 없으면, Null이고, 있다면 그 데이터 
}
```
- 다음은 예시입니다.
```java
{
   isSuccess: true,
   code: 201
   message: "회원가입에 성공했습니다."
   data: null
}
{
   isSuccess: true,
   code: 204
   message: "주문 접수가 완료되었습니다."
   data: null
}
{
   isSuccess: true,
   code: 200
   message: "상품 리스트 조회 성공"
   data: {  
      products: [{
         //.. 생략
         name:"라면",
         price: 30000,
         //.. 생략
      }, {
         //.. 생략
      }],
      pageNumber: 0,
      pageSize: 20,
      totalElement: 33939,
   }
}
{
   isSuccess: false,
   code: 400
   message: "잘못된 요청입니다."
   data: null
}

```

2023-04-29 08:45 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/common/AuthInterceptor.java
> +        if (session == null || session.getAttribute("isAdmin") == null || !(boolean) session.getAttribute("isAdmin")) {
예외를 공부해보니, 시스템에 로그인하지 않은 클라이언트에 대해 401을, 로그인을 했지만 권한이 없는 클라이언트에게는 402를 각각 다르게 보여주는게 좋을 것 같은데, TJ의견은 어떤지 궁금합니다. 그렇게 될 경우 코드는 다음과 같이 작성할 것 같아요!
```java
if (session == null || session.getAttribute("isAdmin") == null || ) {
            response.setStatus(HttpStatus.UNAUTHORIZED.value());
            return false;
}

if(!(boolean) session.getAttribute("isAdmin")) {
            response.setStatus(HttpStatus.FORBIDDEN.value());
            return false;
}
```

2023-04-29 09:56 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderController.java
> +    public ResponseEntity<CompleteOrderReceiptResponse> completeOrderReceipt(@PathVariable("order_uuid") UUID order_uuid) {
- 발생할 수 있는 예외로 다음과 같은 경우를 생각해봤는데, 너무 복잡하게 예외처리하나? 라는 생각도 듭니다. TJ 의견은 어떠신가요?
1. `order_id`의 값이 UUID 형태가 아닌 경우 : 400 Bad Request -> 요쳥 형식에 대한 예외이므로, OrderController에서 처리
2. `order_id`의 값이 UUID 형태이지만, DB에 없는 order_id인 경우 : 404 Not Found -> DB 조회가 필요하므로, OrderService에서 처리
3. DB조회 결과, 실시간 재고량보다 주문 수량이 더 많은 경우 : 409 Conflict -> DB 조회가 필요하므로, OrderService에서 처리

2023-04-30 04:11 UTC, daadaadaah commented on src/test/java/com/hcommerce/heecommerce/common/AuthInterceptorTest.java
> +    @DisplayName("세션이 없는 경우")
위 3개의 DisplayName을 다음과 같이 변경하는게 좀더 의도가 드러나는 테스트 이름일까요?
1. 로그인한 사용자가 관리자인 경우
2. 로그인한 사용자가 관리자가 아닌 경우
3. 로그인하지 않는 사용자인 경우

2023-04-30 19:29 UTC, f-lab-TJ commented on src/main/java/com/hcommerce/heecommerce/order/OrderController.java
> +        orderService.completeOrderReceipt(order_uuid);
HTTP response 코드는 사람들이 고민을 거쳐 만든 정책 (protocol)입니다. 이를 최대한 활용 및 참고하여 만들되, 추가로 필요한 부분이 있다면 추가하면 좋습니다. https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
HTTP는 통신상의 상황에 대한 코드들이 포커스에 맞춰져 있지만, 세부 코드들을 보면 어떤 것이 가장 근접한지 알수도 있습니다. 이를 활용한다면 명시적인 상의가 없이 코드만 보고도 비슷한 결론에 도달할수도 있겠죠?

2023-04-30 19:34 UTC, f-lab-TJ commented on src/main/java/com/hcommerce/heecommerce/order/OrderController.java
> +    public ResponseEntity<CompleteOrderReceiptResponse> completeOrderReceipt(@PathVariable("order_uuid") UUID order_uuid) {
의도되지 않은 입력값은 모두 동일한 결과값을 주어도 될 것 같습니다. 다만, 어떤 값이 들어가야하는지에 대한 정보를 주면 클라이언트 입장에서 편하겠죠?
1. 해당 상황이 실제로 발생할 수 있는지 (발생해도 되는지) 아닌지에 따라 다를 것 같습니다. 발생해도 되는 케이스라면 더 세분화된 예외 코드를, 그렇지 않은 것들은 더 일반적인 예외코드를 줄 것 같습니다. (200, 400, 500은 아래 하위 2xx 4xx 코드들 201, 404, ...을 포함한 상위 코드입니다.)
2. 네 괜찮다고 생각합니다.

2023-04-30 19:36 UTC, f-lab-TJ commented on src/main/java/com/hcommerce/heecommerce/common/AuthInterceptor.java
> +        if (session == null || session.getAttribute("isAdmin") == null || !(boolean) session.getAttribute("isAdmin")) {
해당 코드가 많은 코드에 동일하게 사용될 여지가 있을까요? 있다면 어떻게 코드를 작성하는것이 더 좋은 방법일까요?

2023-04-30 19:37 UTC, f-lab-TJ commented on src/test/java/com/hcommerce/heecommerce/common/AuthInterceptorTest.java
> +    @DisplayName("세션이 없는 경우")
무엇을 테스트하고 싶었는지만 잘 나타나면 됩니다.

2023-05-01 00:43 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderController.java
> +        orderService.completeOrderReceipt(order_uuid);
엇! 제가 좀더 자세히 말씀드렸어야 했는데😅, 제 의도는 response의 body 구조를 저렇게 템플릿화한다는 의미였어요!

2023-05-02 02:45 UTC, daadaadaah commented on src/test/java/com/hcommerce/heecommerce/common/AuthInterceptorTest.java
> +@DisplayName("AuthInterceptor")
<img width="499" alt="스크린샷 2023-05-02 오전 11 44 40" src="https://user-images.githubusercontent.com/60481383/235568527-e1130003-95e7-490b-a44f-0eae0a566769.png">

2023-05-02 04:11 UTC, daadaadaah commented on src/test/java/com/hcommerce/heecommerce/common/AuthHelperTest.java
> +class AuthHelperTest {
<img width="499" alt="스크린샷 2023-05-02 오후 1 11 28" src="https://user-images.githubusercontent.com/60481383/235577661-c78b5a94-6bca-4fe2-8956-cac622ccea1a.png">

2023-05-02 04:13 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/common/AuthInterceptor.java
> +        if (session == null || session.getAttribute("isAdmin") == null || !(boolean) session.getAttribute("isAdmin")) {
Helper 클래스로 만들면 좋을 것 같아서, AuthHelper 클래스를 만들어 보았습니다([3a30f05](https://github.com/f-lab-edu/hee-commerce/pull/8/commits/3a30f0595a45fe8bf8146e0f7b338e54997226fc))

2023-05-02 16:02 UTC, godtaehee commented on src/main/java/com/hcommerce/heecommerce/order/CompleteOrderReceiptResponse.java
> +    UUID order_uuid;
NonNull과 Nullable에 대해서는 말씀해주셔서 처음 알게 됬고, @NotEmpty라는 javax.validation에서 제공해주는 어노테이션은 알고있습니다!

2023-05-03 07:36 UTC, daadaadaah commented on src/test/java/com/hcommerce/heecommerce/order/OrderControllerTest.java
> +                }
현재 이 테스트가 실패하는데, 재고 수량보다 주문 수량이 많은 경우에 대해 어떻게 테스트해야 할까요? 어떻게 respository를 mocking할지? 아니면, repository에 있는 예외 처리 로직을 service나 controller에서 처리하는 걸로 변경해야할지? 등이 고민이네요🤔

2023-05-03 10:06 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/common/AuthInterceptor.java
> +        }
- 현재 코드에서는 다음과 같이 body에 어떠한 것도 넘겨주지 않습니다. 
<img width="1265" alt="스크린샷 2023-05-03 오후 6 59 20" src="https://user-images.githubusercontent.com/60481383/235886644-ae8e6c08-efa9-4b0c-8c78-ec299e090ee3.png">

- @ExceptionHandler 가 붙은 메서드로 예외에 대한 에러 응답처럼 인터셉터에서도 동일한 구조로 처리해줘야 하나? 라는 의문이 드는데, TJ의견은 어떤지 궁금합니다. 
- 코드는 다음과 같이 작성할 것 같고,
```Java

        if (!AuthHelper.isLogin(request)) {
            response.setStatus(HttpStatus.UNAUTHORIZED.value());

            response.setContentType("application/json; charset=UTF-8");

            ObjectMapper objectMapper = new ObjectMapper();
            response.getWriter().append(objectMapper.writeValueAsString(new ErrorResponseDTO("UNAUTHORIZED", "로그인 후에 이용할 수 있습니다.")));
            return false;
        }

        if(!AuthHelper.isAdmin(request)) {
            response.setStatus(HttpStatus.FORBIDDEN.value());

            response.setContentType("application/json; charset=UTF-8");

            ObjectMapper objectMapper = new ObjectMapper();
            response.getWriter().append(objectMapper.writeValueAsString(new ErrorResponseDTO("FORBIDDEN", "관리자만 가능합니다.")));
            return false;
        }

```

- 결과 화면은 다음과 같습니다.
1. 로그인하지 않았을 경우
<img width="1265" alt="스크린샷 2023-05-03 오후 7 04 29" src="https://user-images.githubusercontent.com/60481383/235887658-a17032c9-a87c-4eb4-bfc4-f035ef30dd13.png">
2. 로그인은 했지만 관리자가 아닌 경우
<img width="1265" alt="스크린샷 2023-05-03 오후 7 05 45" src="https://user-images.githubusercontent.com/60481383/235887903-9d806146-87b2-482b-8272-0f442e97af5b.png">

2023-05-03 10:53 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderRestControllerAdvice.java
> +    }
- 각각 `OrderNotFoundException(404)`과 `OrderOverStockException(403)`에 지정해 줬는데, OrderRestControllerAdvice 사용하면서, HTTP 응답 코드가 200으로 나옵니다.
1. `OrderNotFoundException`와 `OrderOverStockException`이 발생할 경우, 이걸 클라이언트한테 404로 던져줄지 200으로 던져줄지 팀 내에서 정하면 되는 건가요?
2. 만약, 404로 던져주고 싶을 때, OrderNotFoundException 에 지정해 놓은 상태코드를 재활용하는 방법이 아닌 아래처럼 다시 annotation을 붙여줘야 하던대. OrderNotFoundException 에 지정해 놓은 상태코드를 재활용하는 방법은 없을까요?
```java
    @ResponseStatus(HttpStatus.FORBIDDEN)
    @ExceptionHandler
    public ErrorResponseDTO orderNotFoundExceptionHandler(OrderNotFoundException e) {
        return new ErrorResponseDTO(HttpStatus.NOT_FOUND.name(), e.getMessage());
    }
```

2023-05-04 03:22 UTC, godtaehee commented on src/main/java/com/hcommerce/heecommerce/common/AuthHelper.java
> +        return session != null && session.getAttribute("isAdmin") != null;
1. Admin이라는게 판매자를 말씀하시는걸까요 ??

2023-05-04 03:54 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/common/AuthHelper.java
> +        return session != null && session.getAttribute("isAdmin") != null;
넵 맞습니다! 저희 쿠팡처럼 판매자가 있는 구매자-판매자-관리자(쿠팡) 구조가 아니라 구매자-`관리자(관리+판매)` 구조라 표현했습니다!

2023-05-04 05:23 UTC, godtaehee commented on src/main/java/com/hcommerce/heecommerce/common/AuthHelper.java
> +        return session != null && session.getAttribute("isAdmin") != null;
판매자인지 아닌지에 대한 판단을 isAdmin이라는 Boolean값으로 관리하는게 너무 간편하지않나? 라는 생각을 했습니다. 판매자가 아닌 악의의 사용자가 isAdmin이라는 값을 true로 해서 요청보내기가 상당히 쉬워보이는데, 이렇게 되면 판매자만 접근 가능해야하는 Resource에 대한 접근이 매우 쉬워질것 같네요

2023-05-04 05:23 UTC, godtaehee commented on src/main/java/com/hcommerce/heecommerce/common/AuthHelper.java
> +        return session != null && session.getAttribute("isAdmin") != null;
Admin이라는 명칭말고 혹시 다른게 있으실까요? 저는 Admin하니까 서비스를 관리하는 회사 내부사람들이 생각이나고, 내부적으로 만드는 Admin페이지 같은 느낌이 나서요!

2023-05-04 05:23 UTC, godtaehee commented on src/main/java/com/hcommerce/heecommerce/order/OrderRestControllerAdvice.java
> +    }
1. 저는 Exception은 200이 아닌 400대의 코드로 보내줘야하는게 맞다고 생각합니다. 그래서 다희님이 저번에 제안 주셨던 응답 구조에서 isSuccess, code도 실제 HTTP status code가 항상 200으로 오는데, code에는 400대의 코드가 온다면 상당히 어색할것 같습니다!

2023-05-04 05:23 UTC, godtaehee commented on src/main/java/com/hcommerce/heecommerce/common/AuthInterceptor.java
> +        }
첫번째 말씀이 잘 이해가 가지 않는데, 제가 @ExceptionHandler를 메소드에 사용하는 코드 예제를 가져왔습니다. 이런식으로 Interceptor를 구성하신다는 말씀하시는건가요?
`@Slf4j
@RestControllerAdvice(basePackages = "hello.exception.api")
public class ExControllerAdvice {

    @ResponseStatus(HttpStatus.BAD_REQUEST)
    @ExceptionHandler(IllegalArgumentException.class)
    public ErrorResult illegalExHandler(IllegalArgumentException e) {
        log.error("[exceptionHandler] ex", e);
        return new ErrorResult("BAD", e.getMessage());
    }

    @ExceptionHandler
    public ResponseEntity<ErrorResult> userExHandler(UserException e) {
        log.error("[exceptionHandler] ex", e);
        ErrorResult errorResult = new ErrorResult("USER-EX", e.getMessage());
        return new ResponseEntity(errorResult, HttpStatus.BAD_REQUEST);
    }

    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
    @ExceptionHandler
    public ErrorResult exHandler(Exception e) {
        log.error("[exceptionHandler] ex", e);
        return new ErrorResult("EX", "내부 오류");
    }

}`

2023-05-04 05:23 UTC, godtaehee commented on src/test/java/com/hcommerce/heecommerce/EnableMockMvc.java
> +            return new CharacterEncodingFilter("UTF-8", true);
이건 어떤건가요?

2023-05-04 05:23 UTC, godtaehee commented on src/test/java/com/hcommerce/heecommerce/common/AuthInterceptorTest.java
> +    void setUp() {
이부분 @Mock Annotation으로 주입을 받지 않으신 이유가 있으실까요? 위의 코드에서는 Annotation으로 주입을 받으신것 같은데 혹시 연습을 위해서라면 죄송합니다

2023-05-04 05:23 UTC, godtaehee commented on src/test/java/com/hcommerce/heecommerce/common/AuthInterceptorTest.java
> +            session.setAttribute("isAdmin", true);
해당 코드도 given, willReturn으로 해볼수 있을것 같습니다!

2023-05-04 05:28 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderRestControllerAdvice.java
> +    }
1. 오! 좋습니다. 400대로 보내주는 걸로 수정할게요!👍

2023-05-04 05:29 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/common/AuthHelper.java
> +        return session != null && session.getAttribute("isAdmin") != null;
hee-commerce 관리자들이 사용하는 admin 페이지 맞아요! 쿠팡처럼 판매자가 있는 구매자-판매자-관리자(쿠팡) 구조가 아니라 구매자-관리자(관리+판매) 구조라서요!ㅎㅎ컬리도 따로 판매자 없고 관리자가 관리하더라구요!

2023-05-04 05:31 UTC, daadaadaah commented on src/test/java/com/hcommerce/heecommerce/EnableMockMvc.java
> +            return new CharacterEncodingFilter("UTF-8", true);
이게 어디있죵?😂

2023-05-04 05:31 UTC, daadaadaah commented on src/test/java/com/hcommerce/heecommerce/common/AuthInterceptorTest.java
> +            session.setAttribute("isAdmin", true);
given, willReturn 공부해보고 적용시켜 보겠습니다!ㅎㅎ

2023-05-04 05:34 UTC, daadaadaah commented on src/test/java/com/hcommerce/heecommerce/common/AuthInterceptorTest.java
> +    void setUp() {
18 ~21 번째 줄 말씀하시는 건가요? 아니면 setup에 붙이시는 걸 말씀하시는 건가요?

2023-05-04 06:49 UTC, f-lab-TJ commented on src/main/java/com/hcommerce/heecommerce/order/OrderController.java
> +    public ResponseEntity<SuccessMessageResponseDTO> completeOrderReceipt(@PathVariable("order_uuid") UUID order_uuid) {
ResponseEntity에 SuccessMessageResponseDTO를 사용한 이유가 뭔가요?
해당 함수는 항상 성공이 보장된 함수인가요?

2023-05-04 06:49 UTC, f-lab-TJ commented on src/main/java/com/hcommerce/heecommerce/order/OrderRestControllerAdvice.java
> +    }
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/server/ResponseStatusException.html
https://www.baeldung.com/spring-response-status-exception

코드에서 작성한 Exception과 Response의 에러 status는 무슨 차이가 있을까요?

2023-05-04 06:49 UTC, f-lab-TJ commented on src/test/java/com/hcommerce/heecommerce/order/OrderControllerTest.java
> +                }
현재 함수 상태에서는 특정 UUID에 대해서 updateToCompleteOrderReceipt를 호출 했을 때 에러를 출력해주도록 해야하지 않을까요?
updateToCompleteOrderReceipt는 따로 테스트 함수를 작성해야 할 것 같습니다.

2023-05-04 07:43 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/common/AuthInterceptor.java
> +        }
3시 사전 모임에서 인터셉터에서도 동일한 구조로 처리해주자! 정함.
결국, 우리 서버의 요청에 대해 에러 상황이라면, 아래와 같은 구조로 메시지를 넘겨주자!
```java
{
    code: "UNAUTHORIZED"
    message: "로그인한 사용자만 이용할 수 있습니다."
}
```

2023-05-04 07:43 UTC, daadaadaah commented on src/test/java/com/hcommerce/heecommerce/EnableMockMvc.java
> +            return new CharacterEncodingFilter("UTF-8", true);
OrderControllerTest 할 때, 한글이 깨지는 문제를 해결하기 위한 어노테이션(@EnableMockMvc)입니다.

2023-05-04 07:43 UTC, daadaadaah commented on src/test/java/com/hcommerce/heecommerce/common/AuthInterceptorTest.java
> +    void setUp() {
@Mock 붙여주는 거랑 안 붙여주는거 어떤 차이가 있는지 공부하기

2023-05-04 09:18 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderController.java
> +    @PatchMapping("/admin/orders/{order_uuid}/order-receipt-complete")
`order_uuid` -> `orderUuid`

2023-05-04 11:52 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderController.java
> +    public ResponseEntity<SuccessMessageResponseDTO> completeOrderReceipt(@PathVariable("order_uuid") UUID order_uuid) {
해당 함수에 실패할 경우, [OrderRestControllerAdvice](https://github.com/f-lab-edu/hee-commerce/pull/8/files#diff-6b3c81b93613590fa5991eb094fd04e418313f7c5bb0cef170243cb56ce4de69)에서 처리하는 구조라서 ResponseEntity에 SuccessMessageResponseDTO를 사용했습니다!

2023-05-04 11:52 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderRestControllerAdvice.java
> +    }
"코드에서 작성한 Exception"인 `OrderNotFoundException`, `OrderOverStockException`가 발생했을 때 난 에러 status와 Response의 에러 status와 어떤 차이가 있는지에 대해 말씀하시는건가여?ㅎㅎ

2023-05-04 11:53 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/CompleteOrderReceiptResponse.java
> +    UUID order_uuid;
Lombok의 NonNull과 Nullable에 대해 한번 공부해보겠습니다!👍

2023-05-04 13:19 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/common/ErrorResponseDto.java
> +}
2. ErrorResponseDto : Lombok의 @Builder나 직접 구현한 빌더 패턴 사용해보기
- 너무 길어서 가독성 좋지 않은 것 같음([예시](https://github.com/daadaadaah/hee-commerce/blob/6f92f9589c6ade6b4d527657fed81c3857388ce8/src/main/java/com/hcommerce/heecommerce/common/AuthInterceptor.java#L25))

2023-05-04 13:19 UTC, daadaadaah commented on src/test/java/com/hcommerce/heecommerce/EnableMockMvc.java
> +public @interface EnableMockMvc {
이게 어떤 원리로 한글이 꺠지는 문제를 해결하는지에 대해 공부하기

2023-05-04 13:19 UTC, daadaadaah commented on src/test/java/com/hcommerce/heecommerce/common/AuthHelperTest.java
> +@ExtendWith(MockitoExtension.class)
어떤 의미에 어노테이션인지 공부하기

2023-05-04 13:19 UTC, daadaadaah commented on src/test/java/com/hcommerce/heecommerce/common/AuthHelperTest.java
> +    @Mock
@Mock을 붙였을 때와 안붙였을 때와 어떤 차이가 있는지 공부하기

2023-05-04 13:19 UTC, daadaadaah commented on src/test/java/com/hcommerce/heecommerce/order/OrderControllerTest.java
> +@AutoConfigureRestDocs
여기 있는 어노테이션들에 대해 공부하기

2023-05-05 04:58 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/common/dto/ErrorResponseDto.java
> +@Getter
https://codenamejy.tistory.com/51

2023-05-06 06:54 UTC, f-lab-TJ commented on src/main/java/com/hcommerce/heecommerce/order/OrderRestControllerAdvice.java
> +    }
네, 자바의 예외 처리와 Response status의 차이요

2023-05-06 06:58 UTC, f-lab-TJ commented on src/main/java/com/hcommerce/heecommerce/order/OrderController.java
> +    public ResponseEntity<SuccessMessageResponseDTO> completeOrderReceipt(@PathVariable("order_uuid") UUID order_uuid) {
이 함수는 심플해서 케이스를 생각하기 어렵겠지만, 예외가 아닌 케이스도 '성공'이 아닌 Response를 내려줘야하는 케이스가 있을 수 있습니다.

2023-05-06 07:02 UTC, f-lab-TJ commented on src/main/java/com/hcommerce/heecommerce/common/ErrorResponseDto.java
> +}
가독성이 좋지 않은 것은 변수 및 클래스명이 긴 것과는 다릅니다. 변수명을 간결하고 적절하게 지정하는 것은 중요하지만, 길다고 가독성이 떨어지는 것은 아니고, 때로는 잘 설명된 (self-explanatory) 변수명이 가독성을 높여줍니다.

2023-05-06 09:58 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/common/ErrorResponseDto.java
> +}
저도 변수 또는 클래스명을 길게해서 의도가 더 잘 드러나면 좋은 코드라고 생각합니다!
다만, 저는 이렇게 매개변수들이 너무 길게 될 경우, 가독성이 떨어지지 않나 라는 생각이 들었습니다. 
지금 생각해보니, 각 매개변수를 변수화 시키거나 가로 정렬해서 사용하면 될 것 같다는 생각이 드네요ㅎㅎ
```
new ErrorResponseDto(HttpStatus.UNAUTHORIZED.name(), "로그인 후에 이용할 수 있습니다.")
```

2023-05-06 16:45 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderController.java
> +    public ResponseEntity<SuccessMessageResponseDTO> completeOrderReceipt(@PathVariable("order_uuid") UUID order_uuid) {
오! 어떤 경우가 있을까? 고민해봤는데, 제가 다음 PR로 관리자가 체크 박스로 여러개를 체크하고 주문 접수 처리를 할 때 사용할 API에서 예를 들어, 10건 중 3건은 주문 접수 불가일 때, 예외가 아닌 실패한 건에 대한 Reponse를 해줘야할 것 같은데, 맞을까요?

2023-05-07 12:29 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderRestControllerAdvice.java
> +    }
제가 질문의 의도를 제대로 파악했는지 모르겠지만, ResponseStatus 는 클라이언트에게 너의 요청에 대한 응답에 대한 답변을 주는 것이 목적이고, 자바에서 예외처리는 현재 서버 상황에 대해 개발자가 파악할 수 있도록 하는 것이 목적이라고 생각합니다. 아...😱 설마, 그래서, 제가 임의로 만든 예외 status와 별개로 response status를 보내줘야되는건가요?

2023-05-10 05:17 UTC, godtaehee approved these changes

2023-05-10 05:17 UTC, godtaehee commented on src/docs/asciidoc/index.adoc
> +include::{snippets}/order-receipt-complete/response-fields.adoc[]
제가 봤을때 이건 정적파일인것 같아서, Resource 폴더에 위치시키는게 어떠신가요?

2023-05-10 05:17 UTC, godtaehee commented on src/test/java/com/hcommerce/heecommerce/common/AuthInterceptorTest.java
> +    void setUp() {
넵 다희님 말씀이 맞습니다.

2023-05-10 05:34 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderRestControllerAdvice.java
> +    }
자바의 예외 처리는 "개발자"에게 던져주는거고, Response status는 "클라이언트"에게 던져주는 거라서, 둘이 다를 수 있다!

2023-05-10 05:36 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderController.java
> +    public ResponseEntity<SuccessMessageResponseDTO> completeOrderReceipt(@PathVariable("order_uuid") UUID order_uuid) {
멘토링 시간에 해결 : `success`라는 단어보다 좀더 범용적인 `messageResponseDto`가 좀더 의도가 드러나는 것 같다.

2023-05-10 05:54 UTC, f-lab-TJ approved these changes

2023-05-10 05:54 UTC, f-lab-TJ commented on src/main/java/com/hcommerce/heecommerce/common/dto/ErrorResponseDto.java
> +public class ErrorResponseDto {
멘토링 시간 이야기한 것과 동일하게 ErrorResponseDto와 Success를 분리해야할지, 그러지 않아도 될지 다시 한번 고민해보고 결정하도록 합시다.

2023-05-11 09:19 UTC, godtaehee commented on src/main/java/com/hcommerce/heecommerce/order/OrderCommandRepository.java
> +        String newOrderStatus = OrderStatus.ORDER_RECEIPT_COMPLETE.name();
OrderStatus를 Enum말고 String으로서 관리하시는건 어떠신가요??

이렇게 되면 Database에 order_status에 0,1,2이런식으로 들어가게 되는건가요?

2023-05-11 09:21 UTC, godtaehee commented on src/main/java/com/hcommerce/heecommerce/order/OrderStatus.java
> +    IN_ORDER_RECEIPT,
여기에서 RECEIPT은 어떤걸 말씀하시는건가요?? 영수증인가요 ??

2023-05-11 09:26 UTC, godtaehee commented on src/main/java/com/hcommerce/heecommerce/order/OrderCommandRepository.java
> +        String newOrderStatus = OrderStatus.ORDER_RECEIPT_COMPLETE.name();
`package com.hcommerce.heecommerce.order;

public interface OrderStatus {
    String IN_ORDER_RECEIPT = "IN_ORDER_RECEIPT";
    String ORDER_RECEIPT_COMPLETE = "ORDER_RECEIPT_COMPLETE";
    String IN_DELIVERY = "IN_DELIVERY";
    String DELIVERY_COMPLETE = "DELIVERY_COMPLETE";
}
`

이렇게 Order Status를 관리하는게 어떤가요???

숫자로 상태를 처리하고, DB에 저장하게 되면 어떤 문제가 발생하나요?

2023-05-11 09:29 UTC, godtaehee commented on src/main/java/com/hcommerce/heecommerce/order/OrderStatus.java
> +    IN_ORDER_RECEIPT,
혹시 주문 진행중이라는것을 뜻하면 PROGRESS_IN_ORDER는 어떤가요???

배송도 진행중이라면 PROGRESS_IN_DELIVERY도 괜찮을것 같은데 다희님 생각은 어떠신가요???

2023-05-11 09:41 UTC, daadaadaah commented on src/docs/asciidoc/index.adoc
> +include::{snippets}/order-receipt-complete/response-fields.adoc[]
태희님 의견대로 바꿔봤는데, 문서가 정상적으로 생성되지 않아요ㅠㅠ 그냥 [공식 문서](https://docs.spring.io/spring-restdocs/docs/3.0.0/reference/htmlsingle/#getting-started-using-the-snippets)에서 지정해준 경로로 가겠습니다!ㅎㅎ

2023-05-11 09:47 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderStatus.java
> +    IN_ORDER_RECEIPT,
> 여기에서 RECEIPT은 어떤걸 말씀하시는건가요?? 영수증인가요 ??
- "주문 접수 중"의 의미에서 "접수"를 뜻하는 의미입니다. 구글 번역 돌려서 최대한 쉬운 단어로 네이밍하고 있긴합니다!ㅎㅎ

> 혹시 주문 진행중이라는것을 뜻하면 PROGRESS_IN_ORDER는 어떤가요???
> 배송도 진행중이라면 PROGRESS_IN_DELIVERY도 괜찮을것 같은데 다희님 생각은 어떠신가요???
- "PROGRESS_IN_DELIVERY" 와 "IN_DELIVERY"는 어떤 차이가 있나요? 저는 "IN_DELIVERY" 만으로 배달 중이라는 의미가 전달되고, 긴것보다 짧은게 글자가 더 실수를 줄일 수 있다고 생각해서 "IN_DELIVERY"로 지었거든요!ㅎㅎ

2023-05-11 09:49 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderCommandRepository.java
> +        String newOrderStatus = OrderStatus.ORDER_RECEIPT_COMPLETE.name();
inteface로 관리할 생각은 못했는데, 태희님 처럼 했을 때에는 어떤 장점이 있나요?
안그래도, order DB 스키마에서 order_status를 숫자로 하고, 참조 테이블 하나 만들려고 했는데, 이부분 내일 사전 미팅에서 같이 이야기해봐요!ㅎㅎ

2023-05-11 10:58 UTC, godtaehee commented on src/docs/asciidoc/index.adoc
> +include::{snippets}/order-receipt-complete/response-fields.adoc[]
아하 넵!

2023-05-11 10:58 UTC, godtaehee commented on src/main/java/com/hcommerce/heecommerce/order/OrderCommandRepository.java
> +        String newOrderStatus = OrderStatus.ORDER_RECEIPT_COMPLETE.name();
자바에서 Enum을 String으로서 사용하려면 Override를 해줘야하는 번거로움이 있더라고요 그래서 간단하게 String Enum을 사용할수 있도록 저런 방식을 찾게되었습니다.

숫자로 했을때 단점은,

저 4가지 상태를 숫자로서 사용하게되면 데이터베이스에 0,1,2,3 이렇게 들어가게 될텐데

데이터베이스를 보고나서 한번에 Order가 어떤 상태인지 숫자만 보고는 알수가 없고

0과 1사이(IN_ORDER_RECEIPT와 ORDER_RECEPIT_COMPLETE)에 만약에 주문 보류라는 새로운 상태가 들어오게 되면 숫자가 하나씩 밀리게 됩니다.

즉, ORDER_RECEIPT_COMPLETE, IN_DELIVERY, DELIVERY_COMPLETE를 기껏 데이터베이스에 1,2,3으로 저장해놨는데 한칸씩 밀리게 되면서 이친구들을 2,3,4로 바꿔주거나 해야하는 번거로운 일이 생깁니다.

다른 PR에서도 언급드렸다 싶히, Magic Number는 전반적으로 좋지않아서 이 부분을 말씀드리려고 했습니다!

2023-05-11 10:58 UTC, godtaehee commented on src/main/java/com/hcommerce/heecommerce/order/OrderCommandRepository.java
> +        String newOrderStatus = OrderStatus.ORDER_RECEIPT_COMPLETE.name();
이처럼, String으로 상태를 표현했을때는 한칸씩 밀리거나 하는 문제도 없고 명확하게 주문의 상태를 알수있어서 숫자를 사용하는것보다는 좋은것 같습니다

2023-05-11 10:58 UTC, godtaehee commented on src/main/java/com/hcommerce/heecommerce/order/OrderStatus.java
> +    IN_ORDER_RECEIPT,
1. 아 그렇군요! 상태에 대한 고민을 좀더 하고있어서 혹시 바뀌게 되면 다시 노티드리겠습니다!
2. 아 IN만 붙혀도 ~하는 중이라고 해석을 하는군요 저는 Progress In혹은 In Progress를 좀 많이 본거같아서 저렇게 말씀드렸던것 같습니다! 알려주셔서 감사합니다!

2023-05-11 10:58 UTC, godtaehee commented on src/main/resources/static/docs/index.html
> +<li><a href="#_주문">주문</a>
이거 HTML을 저희가 만들어야 하는건가요 ?

2023-05-11 11:15 UTC, daadaadaah commented on src/main/resources/static/docs/index.html
> +<li><a href="#_주문">주문</a>
아래 명령어 실행하면 자동으로 문서가 만들어집니다!ㅎㅎ
```
 ./gradlew asciidoc
```

2023-05-11 12:18 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderStatus.java
> +    IN_ORDER_RECEIPT,
1. 좋습니다!
2. 맞아요! 저도 프로젝트 할 때 "Progress"  단어 보긴 했어요!ㅎㅎ근데, 그때 든 생각이 충분히 짧은 단어로도 의미가 드러나는데, 왜 길게 쓰지 라는 생각을 했거든요ㅎㅎ그런데, 이것도 만약에 태희님이 헷갈리시면,  "Progress" 추가해도 상관없다고 생각해요! 이게 태희님이랑 저랑 같이 하는 프로젝트이고, 게다가 주문 도메인은 태희님 담당이니, 담당자가 혼동이 더 없는 걸로 사용하는게 좋다고 생각합니다! 주문 도메인 관련해서 변수명, 함수명 등 태희님이 편한 네이밍이 더 좋을 것 같아서요!ㅎㅎ

2023-05-13 04:11 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/order/OrderCommandRepository.java
> +        String newOrderStatus = OrderStatus.ORDER_RECEIPT_COMPLETE.name();
사전 미팅 결과 : 이펙티브 자바 [아이템 38] 확장할 수 있는 열거 타입이 필요하면 인터페이스를 사용하라 챕터도 참고하기!

2023-05-13 12:09 UTC, daadaadaah commented on src/main/java/com/hcommerce/heecommerce/common/dto/ErrorResponseDto.java
> +public class ErrorResponseDto {
@f-lab-TJ, 위 사항은 PR https://github.com/f-lab-edu/hee-commerce/pull/17 에서 해결되면, 수정하겠습니다!ㅎㅎ

2023-05-15 07:15 UTC, merged